name: Build

on:
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_windows:
    name: build for Windows
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install meson ninja ziglang
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Install WiX
        run: dotnet tool install --global wix
      # - run: scripts/build.ps1
      - run: python scripts/build.py
      - uses: actions/upload-artifact@v3
        with:
          name: artifact_windows
          path: bin/Release/vrmeditor.msi

  create_release:
    name: create release from tag
    runs-on: ubuntu-20.04
    permissions: write-all
    needs: build_windows

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact_windows

      - name: Display structure of downloaded files
        run: ls -R

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          # title: "Release ${{ github.ref }}"
          prerelease: false
          files: |
            vrmeditor.msi
